### ISSUE TITLE
g++ compilation doesn't produce any resulting file

### ISSUE THREAD

**Issue by mcmay** [babun/babun#203]
Hi, my dear friends. I installed the package gcc-g++ on babun under Widnows 7, but when I tried to compile a .cpp file, the compilation seemed to end normally whereas there is no .exe file or any other file resulted. I tried a few other g++ packages, like mingw-gcc-g++, it still didn't work out.
    Please help me out. Thank you very much indeed.

**Comment by ralphjzhang** [comment]
Same issue here, after installing gcc-g++, or clang, running g++ or clang++ gives nothing (normally it should say 'fatal error, no input'), and '127' shows on the right of the prompt, I guess that is the exit code?

**Comment by v-yadli** [comment]
Please check #232. Works for me.

**Comment by mcmay** [comment]
Thank you for your participation in my thread. I've turned back to cygwin, which although does not work as   agilely as babun, does do everything as promised.

**Comment by tombujok** [comment]
It's enough to do what Yatao mentioned -> #232

**Comment by tombujok** [comment]
Fixed in 1.1.0. 
Release status: #266

**Comment by Snorflake** [comment]
I'm still experiencing this
Aria@Aria ~/.vim$ clang
Aria@Aria ~/.vim$ clang --version                                                           127 ↵
Aria@Aria ~/.vim$ babun --version                                                           127 ↵
babun version 1.2.0
Created and maintained by Tom Bujok (@tombujok)
Copyright (c) 2014-2015.
