### ISSUE TITLE
Emacs doesn't run

### ISSUE THREAD

**Issue by dpavlic** [babun/babun#210]
Please forgive if I'm missing something, but emacs-nox (or w32) will not run. Doing a

    pact install emacs

Seems to install the package, but trying to run emacs-nox will not work. Trying to run it from cmd prompt produces "The procedure entry point __cxa_atexit could not be located in the dynamic link library" although I'm not sure if that's relevant.

**Comment by ligun** [comment]
This issue has also appeared in my environment that is Windows7 64bit.
I typed "emacs-nox", but it did not run. And no error message was displayed.

**Comment by mattroid** [comment]
I have a very similar issue with installing the irssi package. The package installs, but when I run the command ">irssi" nothing happens, except for an $? that returns exit code 2. the binary has 777 for testing purposes, so that's not the issue.

**Comment by tombujok** [comment]
It's related to #239 - a fix will come soon...

**Comment by tombujok** [comment]
Fixed in 1.1.0. 
Release status: #266

**Comment by xinglinsky** [comment]
The problem happened again.
![image](https://user-images.githubusercontent.com/20590965/27228620-eb2d964e-52da-11e7-8ab4-534944e160d9.png)
![image](https://user-images.githubusercontent.com/20590965/27228629-ffbecf92-52da-11e7-9c21-b1c2980e6fbb.png)

**Comment by kmcdon** [comment]
Still not working for me either.....

{ ~ }  » emacs                                                                              ~ 127
{ ~ }  » emacs-nox                                                                          ~ 127
{ ~ }  » babun update                                                                       ~ 127
Executing babun update
  upstream  [release]
  installed [1.2.0]
  newest    [1.2.0]
Babun is up to date
Checking Cygwin version:
  installed [1.7.35]
  newest    [1.7.35]
Cygwin is up to date

**Comment by djhaskin987** [comment]
Happening to me too, on a fresh install.

**Comment by verajosemanuel** [comment]
here, same issue. Windows 10 on a fresh babun install.

**Comment by biiont** [comment]
Same issue on fresh babun installation.

Windows 7 SP1, 64-bit

Babun update:
```
Executing babun update
upstream [release]
installed [1.2.0]
newest [1.2.0]
Babun is up to date
Checking Cygwin version:
installed [1.7.35]
newest [1.7.35]
Cygwin is up to date
```
While latest cygwin version is 2.11.2 as of 2019-01-02.

Issue #239 mentions dist-upgrade command, but I was not able to find it neither as part of babum command nor in tools directory.

So I downloaded setup-x86.exe from cygwin site and placed it to `.babun/cygwin/setup` directory and updated cygwin with this utility (verify paths used by cygwin setup).

Now:
```
{ ~ }  » uname -a                                                                        ~
CYGWIN_NT-6.1-WOW L0162447 2.11.2(0.329/5/3) 2018-11-08 14:30 i686 Cygwin
```

But:
```
{ ~ }  » babun update                                                                    ~
Executing babun update
  upstream  [release]
  installed [1.2.0]
  newest    [1.2.0]
Babun is up to date
Checking Cygwin version:
  installed [1.7.35]
  newest    [1.7.35]
Cygwin is up to date
```

Nevertheless emacs works now.

**Comment by nsvir** [comment]
#516 cygwin is not updated with `babun update`
The workaround is to run `.babun/update.bat` manually

After that, emacs is working again :)
