### ISSUE TITLE
crontab weirdness

### ISSUE THREAD

**Issue by jonrobinson2** [babun/babun#212]
Maybe this is just me being very dumb but when I do this:

crontab -e                                                                           ~ 2
no crontab for Jonathan - using an empty one
/bin/sh: /bin/vi: No such file or directory
crontab: "/bin/vi" exited with status 127

Here is my pact show where I have vim installed (vi is aliased to vim in babun via PR 129 https://github.com/babun/babun/pull/129)

{ ~ }  » pact show                                                                              ~
The following packages are installed:
_autorebase
_update-info-dir
alternatives
aspell
aspell-en
attr
autoconf
autoconf2.1
autoconf2.5
automake
automake1.10
automake1.11
automake1.12
automake1.13
automake1.14
automake1.4
automake1.5
automake1.6
automake1.7
automake1.8
automake1.9
base-cygwin
base-files
bash
bc
binutils
bzip2
ca-certificates
compface
coreutils
cpio
cron
crypt
csih
ctags
curl
cvs
cvsps
cygrunsrv
cygutils
cygwin
cygwin-debuginfo
dash
dbus
desktop-file-utils
diffutils
dos2unix
editrights
emacs
emacs-gettext
file
findutils
gamin
gawk
gcc-core
gcc-g++
gcc4-g++
git
git-svn
gnutls
grep
groff
gsettings-desktop-schemas
gzip
ipc-utils
keychain
less
libICE6
libSM6
libX11_6
libXau6
libXaw3d7
libXdmcp6
libXext6
libXmu6
libXpm4
libXt6
libapr1
libaprutil1
libasn1_8
libaspell15
libatomic1
libattr1
libaudio2
libblkid1
libbz2_1
libcloog-isl4
libcom_err2
libcompface0
libcurl4
libdb4.5
libdb4.8
libdbus1_3
libedit0
libevent-devel
libevent2.0_5
libexpat1
libext2fs2
libfam0
libffi4
libffi6
libgcc1
libgdbm4
libglib2.0_0
libgmp10
libgmp3
libgnutls28
libgomp1
libgssapi3
libheimbase1
libheimntlm0
libhogweed2
libhx509_5
libiconv2
libidn11
libintl8
libiodbc2
libisl10
libjbig2
libjpeg62
libjpeg7
libjpeg8
libkafs0
libkrb5_26
libltdl7
liblzma5
libmetalink3
libmpc3
libmpfr4
libmysqlclient18
libncurses-devel
libncurses10
libncurses8
libncurses9
libncursesw-devel
libncursesw10
libneon27
libnettle4
libopenldap2_3_0
libopenldap2_4_2
libopenssl098
libopenssl100
libp11-kit0
libpcre0
libpcre1
libpcre16_0
libpcre32_0
libpcreposix0
libpng12
libpopt0
libpq
libpq5
libproxy1
libreadline6
libreadline7
libroken18
libsasl2
libsasl2_3
libserf1_0
libsigsegv2
libsqlite3_0
libssh2_1
libssp0
libstdc++6
libtasn1_6
libtiff5
libuuid1
libwind0
libwrap0
libxcb1
libxml2
links
login
m4
make
man
mc
mingw64-i686-binutils
mingw64-i686-gcc-core
mingw64-i686-gcc-g++
mingw64-i686-headers
mingw64-i686-runtime
mingw64-i686-winpthreads
mingw64-x86_64-binutils
mintty
nano
nc
ncurses
ncursesw
openssh
openssl
openssl-devel
p11-kit
p11-kit-trust
pcre
perl
perl-Error
perl_vendor
ping
pkg-config
popt
procps
python
readline
rebase
rsync
run
sed
shared-mime-info
shutdown
subversion
subversion-perl
tar
terminfo
terminfo-extra
terminfo0
texinfo
time
tree
tzcode
unzip
util-linux
vim
vim-common
w32api-headers
w32api-runtime
wget
which
xemacs
xemacs-emacs-common
xxd
xz
zlib-devel
zlib0
zsh

Please tell me if you need more info

**Comment by tombujok** [comment]
Fixed in 1.1.2
See release status: #304

**Comment by AnthonyWC** [comment]
This issues still exist in 1.2:

```
babun version 1.2.0
Created and maintained by Tom Bujok (@tombujok)
Copyright (c) 2014-2015.

antho@stratus  /etc/cron.daily  crontab -e
no crontab for antho - using an empty one
/bin/sh: /bin/vi: cannot execute binary file: Exec format error
crontab: "/bin/vi" exited with status 126

```
"ln -s /bin/vim.exe vi.exe" still gives error but "export EDITOR=vim" fixs it.

**Comment by roszel** [comment]
@AnthonyWC  Thanks a lot!
"**export EDITOR=vim**"  
this solved my problem on raspbian_Sept-2016 :
+ - - - - - - - **Here the error message I got** - - - - - - - - - - - - +
pi@####:~/Downloads $ crontab -e
/bin/sh: 1: /usr/share/vim: Permission denied
crontab: "/usr/share/vim" exited with status 126
+ - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - +
