### ISSUE TITLE
Command exits with 127 on Babun, but works on Cygwin

### ISSUE THREAD

**Issue by kehak** [babun/babun#225]
Running smartctl on Babun exits silently with error code 127, however running the same binary from a vanilla Cygwin installation works.

» pact install smartmontools
(...)
» /usr/sbin/smartctl -A /dev/sda                            ~127
» bash /usr/sbin/smartctl -A /dev/sda                   ~125
/usr/sbin/smartctl.exe: /usr/sbin/smartctl.exe: cannot execute binary file

Same problem when running the Cygwins smartctl from Babun, even though the reverse works (running Babuns smartctl from Cygwin).

» ls -l /usr/sbin/smartctl.exe                                                           ~
-rwxr-xr-x+ 1 Kehak None 0 Jan 11 18:06 /usr/sbin/smartctl.exe
» file /usr/sbin/smartctl.exe                                                            ~
/usr/sbin/smartctl.exe: PE32 executable (console) Intel 80386, for MS Windows

Tried running Babun as administrator, no difference.

**Comment by darinkes** [comment]
Just a wild guess: see Issue #222
Maybe pact is also not running postinstall scripts while installing smartmontools.
(Didn't check if smartmontool has any)

**Comment by darinkes** [comment]
Yes, seems to be the same problem:
```
Package smartmontools installed
{ ~ }  » ls -l /etc/postinstall/*.sh
-rwxrwxr-x+ 1 user Kein 274 Sep  7 18:21 /etc/postinstall/smartmontools.sh
```

**Comment by tombujok** [comment]
Will be fixed soon, there's a PR waiting for merge.

**Comment by NobbZ** [comment]
ruby and emacs seem to be affected by this too.

Is there a way to install from pullrequest until it is merged and a working version deployed?

**Comment by tombujok** [comment]
Fixed in 1.1.0. 
Release status: #266

**Comment by masaeedu** [comment]
Still seeing a similar issue with the python binary, although I'm using babun 1.2.0

**Comment by aeroreyna** [comment]
Still same problem

**Comment by henriklewander** [comment]
Same problem for me also but there are now *.sh files, only *.sh.done

**Comment by henriklewander** [comment]
OK, it seems info in last post https://github.com/babun/babun/issues/222 actually fixed it:

Run update.bat from the .babun directory after exiting all babun instances and after updating everything it works.

**Comment by TomyLobo** [comment]
To everyone reading the above comment by @henriklewander:
Make absolutely sure you are running this as admin and you are *NOT* interrupting it!
That's what I did and it fried my babun installation.
Ran without admin rights, noticed the errors, cancelled the installation and *everything* was gone.

**Comment by axellejamous** [comment]
Also to everyone reading the above comment by @henriklewander:
If you're a noob like me and you're wondering where to find the .babun dir to run update.bat it's in your User's folder
