### ISSUE TITLE
Vim stopped working after pact update vim

### ISSUE THREAD

**Issue by tkossak** [babun/babun#424]
I tried updating vim with `pact update vim` and to my surprise pact started first removing vim and some libraries (!) and then installing it anew. From now on the vim doesn't work at all. When i run `vim` nothing happens - just the next prompt appears. Any ideas how to fix it? I tried `babun update` but it didn't help.

```sh
{ ~ }  » babun update
Executing babun update
  upstream  [release]
  installed [1.2.0]
  newest    [1.2.0]
Babun is up to date
Checking Cygwin version:
  installed [1.7.35]
  newest    [1.7.35]
Cygwin is up to date
{ ~ }  » pact install vim
Working directory is /setup
Mirror is http://mirrors.kernel.org/sourceware/cygwin/
setup.ini taken from the cache
Package vim is already installed, skipping
{ ~ }  » vim
{ ~ }  » pact update vim
Removing vim
Package vim removed
Working directory is /setup
Mirror is http://mirrors.kernel.org/sourceware/cygwin/
setup.ini taken from the cache

Installing vim
Found package vim
File ‘vim-7.4.838-1.tar.xz’ already there; not retrieving.

Unpacking...
Package vim requires the following packages, installing:
bash cygwin libgcc1 libiconv2 libintl8 libncursesw10 libssp0 vim-common
Package bash is already installed, skipping
Package cygwin is already installed, skipping
Package libgcc1 is already installed, skipping
Package libiconv2 is already installed, skipping
Package libintl8 is already installed, skipping
Package libncursesw10 is already installed, skipping
Package libssp0 is already installed, skipping
Package vim-common is already installed, skipping
Package vim installed
{ ~ }  » vim
{ ~ }  » which vim
/usr/bin/vim
{ ~ }  » type /usr/bin/vim
/usr/bin/vim is /usr/bin/vim
{ ~ }  » file /usr/bin/vim
/usr/bin/vim: PE32 executable (console) Intel 80386, for MS Windows
{ ~ }  »
```

**Comment by tombujok** [comment]
It may be related to the fact the we are still on Cygwin 1.7.35 - we should
update to 2.x.
I wrote an email related to that - will be publishing it soon (CC: @jlupi)

@jlupi - could you guys at SBB spend an hour and test babun with Cygwin
2.x? It's a blocker for now...

**Comment by tombujok** [comment]
We need some feedback here. Could anybody retest it?

**Comment by jlupi** [comment]
@tombujok I run babun on cygwin 2.x for about three weeks. So far so good. Will try vim update tomorrow.

**Comment by jlupi** [comment]
I had cygwin 2.0.4 and tried pact update vim. It didnt work indeed. Installing the most recent cygwin resolved the issue. 

````
{ ~ }  » uname -a                                                                               ~
CYGWIN_NT-6.1-WOW K11263 2.2.1(0.289/5/3) 2015-08-20 11:40 i686 Cygwin
````

We'll release babun with the newest cygwin version soon.

**Comment by hank** [comment]
Is there any way we can try the new cygwin now?  My vim is completely broken.  Is there a way I can pull the old vim from somewhere in the meantime?

**Comment by irightcode** [comment]
Same here. A workaround would be appreciate or an explanation on how to upgrade the cygwin could work also. Thank you.

**Comment by hank** [comment]
This fixed it for me: http://stackoverflow.com/questions/25280199/how-to-upgrade-git-in-babun/25547715#25547715

**Comment by irightcode** [comment]
yeah that worked. That was simple. Thanks

**Comment by bwlv** [comment]
the meat of the SO link @hank shared above:

> 
> Update your installation by using Cygwin installer:
> 
> 1. Download Cygwin installer from http://cygwin.com/setup-x86.exe
> 2. Run the installer and use your .babun\cygwin directory (most likely C:\Users\your-username\.babun\cygwin) as the root install directory
> 3. Click through the installer. By default, it upgrades all packages.
>

**Comment by Swoorup** [comment]
My vim too is completely broken now. The SO solution doesn't work :(

**Comment by kraluk** [comment]
@Swoorup - maybe is not too late - you should try to run the update.bat script, which is located in your Babun directory (for default installation it will be `C:\Users\$USER\.babun\update.bat` ).

Mentioned script will update whole Cygwin distribution (with Vim two) - in mine case Vim came back to life in a newer version after that operation :)

**Comment by Swoorup** [comment]
@kraluk I fixed this by doing a full cygwin 2.874 update as **bwlv** mentioned. Looks like the later versions of vim requires updated version of cygwin shared libraries.

Hope, we get a babun update soon to 64 bit + latest

My current babun setup :smiley: 
![alt text] (http://i.imgur.com/IXWBiDz.png)

**Comment by Explorare** [comment]
@Swoorup Hi, is that tmux in the image? Could u please share the config file with [me](explorare@hencolle.com)? It's beautiful. Thanks.

**Comment by kielstrand** [comment]
As already mentioned in another thread, did you try upgrading using the upgrade script from babun? this also upgrades cygwin and all packages installed by pact.

this solved the issues for me.

**Comment by Swoorup** [comment]
@Explorare http://swoorupjoshi.xyz/blog/unixing-your-windows-environment/

Sorry but I now use cygwin and msys2 instead

**Comment by tkossak** [comment]
@kielstrand I fixed this issue by upgrading from Windows to GNU/Linux :). No more problems for me.

**Comment by feryardiant** [comment]
For anyone who still facing this issue, you should execute `update.bat` under your babun directory and everything will fixed.

P.S: I've tried @bwlv solution but got no luck, a tons of error popups appears and I have no idea what to do until I found https://github.com/babun/babun/issues/720#issuecomment-264421361

**Comment by ralberts** [comment]
@Swoorup I love your layout!  I am curious - what is the bottom right window composed of?  I love the line number and the bottom bar - curious what you had to install / configure to do that :-)

**Comment by CatLover91** [comment]
@Explorare @ralberts I believe you guys are referencing [powerline](https://github.com/erikw/tmux-powerline)

**Comment by Explorare** [comment]
@CatLover91 Thanks : )

**Comment by stroparo** [comment]
Indeed, powerline fonts have special characters and allow for those "arrow" delimiters in prompts and statuses.
