### ISSUE TITLE
compaudit:74: _i_addfiles: assignment to invalid subscript range

### ISSUE THREAD

**Issue by zou-mono** [babun/babun#736]
HI, everyone. Recently I got a strange problem after running babun as non-admin:
`compaudit:74: _i_addfiles: assignment to invalid subscript range` 
which causes the auto-completion is not working.  But if I run babun as admin, everything is OK.
I have browsed many solutions from babun, zsh and cygwin  discussion group, and doubt this problem is caused by .zcompdump file. I have followed this approach `rm -f ~/.zcompdump*; compinit`, but not working. I realize that If I run as admin, the  .zcompdump file will have many content, but if I run as non-admin, this file is  almost empty. Although I copy the content from .zcompdump to overwrite the empty ones, but if I restart babun as non-admin, it still empty. 
Now I can continue my work as admin, but I still want to know what happen as non-admin. If the file access permission or other reason?

**Comment by zou-mono** [comment]
It have been solved by reinstall. Maybe some file access permission to be modified during other operation.

**Comment by Jiffies-Duke** [comment]
This is because of Windows file permissions. Babun sets  zsh folder permission to "refuse" for current user. After change the permission to "full control" , this error message disappeared.

**Comment by bn3t** [comment]
I tried to reset permissions to my zsh folder but it didn't fix the problem. I had to reinstall babun. I hope this bug does not show up too often.
